### ISSUE TITLE
duplicati q's

### ISSUE THREAD

**Issue by joscha** [klutchell/balena-homeassistant#773]
Hello,

I recently started using this project and have a few questions:

* Is there a specific reason we're on [`linuxserver/duplicati:v2.0.6.3-2.0.6.3_beta_2021-06-17-ls154@sha256:bcd89eb054ff1bce2c438d5eaab39120ab71580d44317c41a65a8e1fd91fbda5`](https://github.com/klutchell/balena-homeassistant/blob/d272f81ce2a6acd39aac2f6e90c9262c5cdc0e48/docker-compose.yml#L88C12-L88C144) and not `lscr.io/linuxserver/duplicati:latest` ?
* Why do we `--webservice-interface=any` and not bind to `SET_HOSTNAME`?
* `linuxserver/duplicati` has a `TZ` env var, should we forward the one we have set for the balena fleet?
* Which folders do I want to add to my backup? Anything in `/volumes/` or anything in `/volumes/config`?
* Would it make sense for us to pre-define a config of some sort that contains all necessary sources?

**Comment by klutchell** [comment]
> Is there a specific reason we're on [linuxserver/duplicati:v2.0.6.3-2.0.6.3_beta_2021-06-17-ls154@sha256:bcd89eb054ff1bce2c438d5eaab39120ab71580d44317c41a65a8e1fd91fbda5](https://github.com/klutchell/balena-homeassistant/blob/d272f81ce2a6acd39aac2f6e90c9262c5cdc0e48/docker-compose.yml#L88C12-L88C144) and not lscr.io/linuxserver/duplicati:latest ?

Because using a latest tag can accidentally introduce changes without anyone noticing. The tag should be pretty close if not the same as latest anyway. Do a search for `why not to use latest docker tags`.

> Why do we --webservice-interface=any and not bind to SET_HOSTNAME?

Because a hostname is not the same as an interface IP for binding. Also SET_HOSTNAME only needs to be applied to the hostname service, not all services.

> linuxserver/duplicati has a TZ env var, should we forward the one we have set for the balena fleet?

When it is set at the fleet level it is applied to all services

> Which folders do I want to add to my backup? Anything in /volumes/ or anything in /volumes/config?

Up to you, I back up everything in /volumes but /volumes/config is the most important

> Would it make sense for us to pre-define a config of some sort that contains all necessary sources?

A backup config usually also requires a destination and encryption password, which would differ for every user. I don't think there would be much value in a default config that doesn't have a backup destination.
